[project]
name = "rpweave"
version = "0.1.0"
description = "Integrated R+Python document system"
requires-python = ">=3.8"

dependencies = [
    "pandas",
    "numpy",
    "matplotlib",
    "scipy",
    "plotly",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"